name: molecule-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0
  - appnope=0.1.3
  - ase=3.22.1
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blas=1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - bokeh=3.2.1
  - boost=1.74.0
  - boost-cpp=1.74.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=2.2.1
  - comm=0.1.4
  - contourpy=1.0.5
  - cryptography=41.0.4
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2023.9.2
  - dav1d=1.2.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - dill=0.3.7
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - filelock=3.9.0
  - flask=2.3.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - fsspec=2023.9.2
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.14
  - graphviz=2.50.0
  - greenlet=2.0.1
  - gts=0.7.6
  - h5py=3.7.0
  - harfbuzz=4.4.1
  - hdf5=1.12.1
  - icu=70.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.31.1
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2023.1.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - isodate=0.6.1
  - itsdangerous=2.1.2
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libtool=2.4.7
  - libuv=1.44.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=16.0.6
  - llvmlite=0.40.0
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numba=0.57.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=3.1.3
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=2.0.3
  - pango=1.50.7
  - parallel-hashmap=1.33
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre=8.45
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycairo=1.23.0
  - pycparser=2.21
  - pyg-lib=0.2.0
  - pygments=2.16.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.1
  - rdflib=7.0.0
  - rdkit=2022.03.5
  - readline=8.2
  - reportlab=3.5.67
  - requests=2.31.0
  - scikit-image=0.19.3
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - setuptools=68.2.2
  - six=1.16.0
  - snappy=1.1.10
  - sqlalchemy=1.4.39
  - sqlite=3.43.0
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - sympy=1.11.1
  - tabulate=0.9.0
  - tbb=2021.8.0
  - threadpoolctl=3.2.0
  - tifffile=2023.4.12
  - tk=8.6.13
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.10.0
  - trimesh=3.23.5
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - werkzeug=2.3.7
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torch==2.0.1
      - torch-geometric==2.3.1
