name: environment

dependencies:
  - python=3.10
  - numpy
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - tqdm
  - pytorch
  # - torch_geometric
  # - rdkit
  # - deepchem
  # - datamol
  # - molfeat
  # - pip:
  #   - pip install datamol
  #   - pip install molfeat